# See the syntax docs at
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Todos To Issue GitHub Action
description: It scans your source code looking for TODO comments and creates an issue with them

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  github-branch:
    description: 'Current repository branch'
    require: true
  pattern:
    description: 'Pattern to match'
    required: false
    default: 'TODO'
  scan-dir:
    description: 'Scan directory'
    required: false
    default: '.'
  exclude-dirs:
    description: 'Directories to exclude during the scan'
    required: false
    default: 'node_modules,.github'
  scan-extensions:
    description: 'Specify the files extensions to scan'
    required: false
    default: '.js,.ts,.cjs,.mjs'


runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'x'
  color: 'gray-dark'