name: notify-release
on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'
  release:
    types: [published]
  issues:
    types: [closed]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Notify release
        uses: nearform-actions/github-action-notify-release@v1
