name: Create a release
on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver to use
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Node.js runtime on build
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
      - uses: nearform-actions/optic-release-automation-action@v4
        with:
          semver: ${{ github.event.inputs.semver }}
          commit-message: 'chore: release {version}'
          sync-semver-tags: true
          build-command: |
            echo 'installing husky hooks..'
            npm ci
